import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const repoRoot = path.resolve(__dirname, '..');
const nodePackageJsonPath = path.join(repoRoot, 'package.json');
const PACKAGE_NAME = JSON.parse(fs.readFileSync(nodePackageJsonPath, 'utf8')).name;

const inputPath = path.join(__dirname, 'test-full.md');
const outputPath = path.join(__dirname, 'test-full.docx');

async function loadApi() {
  try {
    return await import(PACKAGE_NAME);
  } catch (e) {
    const fallback = path.join(repoRoot, '../dist/index.mjs');
    if (fs.existsSync(fallback)) {
      console.warn(`[test] Failed to import "${PACKAGE_NAME}", falling back to ${fallback}`);
      return await import(pathToFileURL(fallback).href);
    }
    throw e;
  }
}

async function main() {
  const api = await loadApi();
  console.log('[test] imported:', PACKAGE_NAME);
  console.log('[test] exports:', Object.keys(api).sort().join(', '));

  if (!fs.existsSync(inputPath)) {
    fs.writeFileSync(
      inputPath,
      '# md2docx API test\n\nThis file is generated by `node/test.mjs`.\n\n- item 1\n- item 2\n',
      'utf8'
    );
    console.log(`[test] created: ${inputPath}`);
  }
  if (typeof api.markdownFileToDocxFile !== 'function') {
    throw new Error('API is missing markdownFileToDocxFile()');
  }

  console.log(`[test] converting: ${inputPath}`);
  await api.markdownFileToDocxFile(inputPath, outputPath, { theme: 'default' });
  console.log(`[test] wrote: ${outputPath}`);
}

main().catch((err) => {
  const msg = err instanceof Error ? err.stack || err.message : String(err);
  console.error('[test] failed:', msg);
  console.error('\n[test] If you have not built the CLI yet, run: pnpm node');
  process.exit(1);
});
